[shell]
program = "/bin/fish"
args = [ "-l", "-c", "tmux" ]

[window]
dynamic_padding = false
decorations = "None"
opacity = 0.8

[font]
size = 23

	[font.normal]
	family = "AnonymicePro Nerd Font"
	style = "Regular"

	[font.bold]
	family = "AnonymicePro Nerd Font"
	style = "Bold"

	[font.italic]
	family = "AnonymicePro Nerd Font"
	style = "Italic"

	[font.bold_italic]
	family = "AnonymicePro Nerd Font"
	style = "Bold Italic"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "PasteSelection"
